<?php

return [
    'catalog' => [
        1 => [
            'id' => 1,
            'title' => 'Neon Harbor',
            'director' => 'Ava Chen',
            'year' => 2024,
            'genre' => 'Sci-Fi',
            'runtime' => '2h 8m',
            'rating' => '10/10',
            'poster' => 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=600&h=900&q=80',
            'backdrop' => 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=1600&h=900&q=80',
            'synopsis' => 'A rain-soaked port city hides a smuggling ring that trades in stolen memories. When a dock worker finds a reel that should not exist, she has one night to decide who gets to remember the truth.',
            'comments' => [
                [
                    'author' => 'Maya R.',
                    'time' => '2 days ago',
                    'body' => 'That last shot on the harbor lights is unforgettable. Perfect 10.',
                ],
                [
                    'author' => 'Chris L.',
                    'time' => '1 week ago',
                    'body' => 'Ava Chen’s pacing is so confident. I rewatched it the same night.',
                ],
            ],
        ],
        2 => [
            'id' => 2,
            'title' => 'The Last Frame',
            'director' => 'Marcus Hale',
            'year' => 2023,
            'genre' => 'Drama',
            'runtime' => '1h 54m',
            'rating' => '10/10',
            'poster' => 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?auto=format&fit=crop&w=600&h=900&q=80',
            'backdrop' => 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?auto=format&fit=crop&w=1600&h=900&q=80',
            'synopsis' => 'An aging projectionist discovers that every film he screens is missing its final frame — and that the missing images are rewriting his own life.',
            'comments' => [
                [
                    'author' => 'Elena K.',
                    'time' => '3 days ago',
                    'body' => 'Quiet, patient, and devastating. The theater scenes feel sacred.',
                ],
            ],
        ],
        3 => [
            'id' => 3,
            'title' => 'Desert Echo',
            'director' => 'Priya Nair',
            'year' => 2025,
            'genre' => 'Thriller',
            'runtime' => '1h 47m',
            'rating' => '10/10',
            'poster' => 'https://images.unsplash.com/photo-1509316785289-025f5b846b35?auto=format&fit=crop&w=600&h=900&q=80',
            'backdrop' => 'https://images.unsplash.com/photo-1509316785289-025f5b846b35?auto=format&fit=crop&w=1600&h=900&q=80',
            'synopsis' => 'A radio operator in the empty interior starts receiving a transmission from a vanished expedition. The more she answers, the closer the desert comes.',
            'comments' => [
                [
                    'author' => 'Jonah P.',
                    'time' => '5 days ago',
                    'body' => 'Sound design of the year. I still hear that static.',
                ],
            ],
        ],
        4 => [
            'id' => 4,
            'title' => 'Midnight Signal',
            'director' => 'Leo Park',
            'year' => 2022,
            'genre' => 'Mystery',
            'runtime' => '2h 1m',
            'rating' => '10/10',
            'poster' => 'https://images.unsplash.com/photo-1536440136628-849c8d64a004?auto=format&fit=crop&w=600&h=900&q=80',
            'backdrop' => 'https://images.unsplash.com/photo-1536440136628-849c8d64a004?auto=format&fit=crop&w=1600&h=900&q=80',
            'synopsis' => 'A late-night DJ realizes callers are describing crimes that have not happened yet. To stop the next one, she has to stay on air until dawn.',
            'comments' => [
                [
                    'author' => 'Sofia D.',
                    'time' => '4 hours ago',
                    'body' => 'Leo Park turns a radio booth into a thriller set. Loved every minute.',
                ],
            ],
        ],
        5 => [
            'id' => 5,
            'title' => 'Glass Orchard',
            'director' => 'Elena Voss',
            'year' => 2024,
            'genre' => 'Romance',
            'runtime' => '1h 52m',
            'rating' => '10/10',
            'poster' => 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=600&h=900&q=80',
            'backdrop' => 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=1600&h=900&q=80',
            'synopsis' => 'Two conservators restoring a greenhouse of blown-glass trees fall in love while the collection begins to bloom on its own.',
            'comments' => [
                [
                    'author' => 'Noah T.',
                    'time' => '1 day ago',
                    'body' => 'Visually stunning. The greenhouse at night is a 10/10 image.',
                ],
            ],
        ],
        6 => [
            'id' => 6,
            'title' => 'Winter Circuit',
            'director' => 'Jonah Reed',
            'year' => 2021,
            'genre' => 'Action',
            'runtime' => '2h 14m',
            'rating' => '10/10',
            'poster' => 'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=600&h=900&q=80',
            'backdrop' => 'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=1600&h=900&q=80',
            'synopsis' => 'An ice-road courier is forced into a high-stakes relay across a frozen city when her last package turns out to be a person.',
            'comments' => [
                [
                    'author' => 'Amina S.',
                    'time' => '6 days ago',
                    'body' => 'Practical stunts, brutal cold, and a director who never lets go.',
                ],
            ],
        ],
        7 => [
            'id' => 7,
            'title' => 'Paper Planets',
            'director' => 'Mei Tanaka',
            'year' => 2025,
            'genre' => 'Family',
            'runtime' => '1h 38m',
            'rating' => '10/10',
            'poster' => 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?auto=format&fit=crop&w=600&h=900&q=80',
            'backdrop' => 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?auto=format&fit=crop&w=1600&h=900&q=80',
            'synopsis' => 'A shy student folds origami worlds that come alive after dark. When one planet goes missing, she has to travel through her own sketches to bring it home.',
            'comments' => [
                [
                    'author' => 'Liam W.',
                    'time' => '2 weeks ago',
                    'body' => 'Warm, inventive, and endlessly kind. A perfect family 10.',
                ],
            ],
        ],
        8 => [
            'id' => 8,
            'title' => 'Velvet Static',
            'director' => 'Omar Idris',
            'year' => 2023,
            'genre' => 'Horror',
            'runtime' => '1h 41m',
            'rating' => '10/10',
            'poster' => 'https://images.unsplash.com/photo-1594909122845-11baa439b7bf?auto=format&fit=crop&w=600&h=900&q=80',
            'backdrop' => 'https://images.unsplash.com/photo-1594909122845-11baa439b7bf?auto=format&fit=crop&w=1600&h=900&q=80',
            'synopsis' => 'A vintage CRT television in a boarded-up cinema still broadcasts a late show. Viewers who finish the program are never seen leaving the lobby.',
            'comments' => [
                [
                    'author' => 'Harper J.',
                    'time' => '8 hours ago',
                    'body' => 'Creepy without cheap jumps. Omar Idris knows how to hold a shot.',
                ],
            ],
        ],
    ],
];
